name: Publish to PyPI

on:
  push:
    branches: [ "main" ]





jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
        python -m pip install setuptools wheel
        python -m pip install --upgrade twine
        
    - name: Build the package
      run: |
        rm -rf dist/ build/ *.egg-info
        python -m build


    - name: Publish to PyPI
      env:
        USERS : __token__
        PASWD : ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m twine upload  -u $USERS -p  $PASWD  dist/* 
